services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cinemate
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: